[workspace.package]
version = "1.0.0"

[workspace]
resolver = "3"
members = [
    "modules/adapters",
    "modules/application",
    "modules/core",
    "modules/domain"
]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
async-trait = "0.1.89"
serde = "1.0.228"
tokio = "1.48.0"
axum = "0.8.6"
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
